services:
  - type: web
    name: campus-booking-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: smart-campus-booking
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: MAIL_FROM
        sync: false
      - key: CLIENT_URL
        value: https://campus-booking-app.onrender.com
      - key: CLIENT_URLS
        value: https://campus-booking-app.onrender.com,http://localhost:5173,http://127.0.0.1:5173

staticSites:
  - name: campus-booking-app
    rootDir: client
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://campus-booking-api.onrender.com/api
